// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/tx.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitBundle represents a message to submit a bundle of transactions
type MsgSubmitBundle struct {
	Sender       string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Transactions [][]byte   `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BlockHeight  int64      `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BundleFee    types.Coin `protobuf:"bytes,4,opt,name=bundle_fee,json=bundleFee,proto3" json:"bundle_fee"`
}

func (m *MsgSubmitBundle) Reset()         { *m = MsgSubmitBundle{} }
func (m *MsgSubmitBundle) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBundle) ProtoMessage()    {}
func (*MsgSubmitBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2871739d4618116, []int{0}
}
func (m *MsgSubmitBundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBundle.Merge(m, src)
}
func (m *MsgSubmitBundle) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBundle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBundle proto.InternalMessageInfo

func (m *MsgSubmitBundle) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSubmitBundle) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *MsgSubmitBundle) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgSubmitBundle) GetBundleFee() types.Coin {
	if m != nil {
		return m.BundleFee
	}
	return types.Coin{}
}

// MsgSubmitBundleResponse defines the response structure for executing a
// MsgSubmitBundle message
type MsgSubmitBundleResponse struct {
	BundleId string `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
}

func (m *MsgSubmitBundleResponse) Reset()         { *m = MsgSubmitBundleResponse{} }
func (m *MsgSubmitBundleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBundleResponse) ProtoMessage()    {}
func (*MsgSubmitBundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2871739d4618116, []int{1}
}
func (m *MsgSubmitBundleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBundleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBundleResponse.Merge(m, src)
}
func (m *MsgSubmitBundleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBundleResponse proto.InternalMessageInfo

func (m *MsgSubmitBundleResponse) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgSubmitBundle)(nil), "seiprotocol.seichain.mev.MsgSubmitBundle")
	proto.RegisterType((*MsgSubmitBundleResponse)(nil), "seiprotocol.seichain.mev.MsgSubmitBundleResponse")
}

func init() { proto.RegisterFile("v1/tx.proto", fileDescriptor_c2871739d4618116) }

var fileDescriptor_c2871739d4618116 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x33, 0xe6, 0x72, 0xf1, 0x4e, 0x03, 0x42, 0x10, 0x8d, 0x15, 0x62, 0xec, 0x2a, 0x82,
	0x9d, 0x21, 0x57, 0x71, 0xe9, 0xa2, 0xc2, 0x45, 0x17, 0x77, 0x13, 0x77, 0x6e, 0x4a, 0x26, 0x39,
	0x4d, 0x86, 0x26, 0x73, 0x4a, 0xcf, 0x24, 0xe8, 0x5b, 0xf8, 0x28, 0x3e, 0x46, 0x97, 0x5d, 0xba,
	0x12, 0x69, 0x5f, 0x44, 0x9a, 0xc4, 0x45, 0x0b, 0x82, 0xbb, 0x33, 0xdf, 0xf9, 0x87, 0xff, 0x9b,
	0xe1, 0x93, 0x2e, 0x91, 0xf6, 0xab, 0xd8, 0x6c, 0xd1, 0xa2, 0x1f, 0x10, 0xe8, 0x7e, 0xca, 0xb1,
	0x16, 0x04, 0x3a, 0xaf, 0x32, 0x6d, 0x44, 0x03, 0xdd, 0xf4, 0x71, 0x89, 0x25, 0xf6, 0x2b, 0x79,
	0x9a, 0x86, 0xfc, 0x34, 0xcc, 0x91, 0x1a, 0x24, 0xa9, 0x32, 0x02, 0xd9, 0x25, 0x0a, 0x6c, 0x96,
	0xc8, 0x1c, 0xb5, 0x19, 0xf6, 0xb3, 0x1f, 0x8c, 0x3f, 0xba, 0xa7, 0xf2, 0x73, 0xab, 0x1a, 0x6d,
	0x17, 0xad, 0x29, 0x6a, 0xf0, 0x9f, 0xf0, 0x6b, 0x02, 0x53, 0xc0, 0x36, 0x60, 0x11, 0x8b, 0x6f,
	0xd2, 0xf1, 0xe4, 0xcf, 0xb8, 0x67, 0xb7, 0x99, 0xa1, 0x2c, 0xb7, 0x1a, 0x0d, 0x05, 0x0f, 0x22,
	0x37, 0xf6, 0xd2, 0x33, 0xe6, 0xbf, 0xe4, 0x9e, 0xaa, 0x31, 0x5f, 0x2f, 0x2b, 0xd0, 0x65, 0x65,
	0x03, 0x37, 0x62, 0xb1, 0x9b, 0x4e, 0x7a, 0xf6, 0xb1, 0x47, 0xfe, 0x7b, 0xce, 0x55, 0x5f, 0xb4,
	0x5c, 0x01, 0x04, 0x57, 0x11, 0x8b, 0x27, 0xb7, 0xcf, 0xc4, 0xe0, 0x29, 0x4e, 0x9e, 0x62, 0xf4,
	0x14, 0x1f, 0x50, 0x9b, 0xc5, 0xd5, 0xee, 0xd7, 0x0b, 0x27, 0xbd, 0x19, 0xae, 0xdc, 0x01, 0xcc,
	0xde, 0xf1, 0xa7, 0x17, 0xc6, 0x29, 0xd0, 0x06, 0x0d, 0x81, 0xff, 0x9c, 0x8f, 0xb9, 0xa5, 0x2e,
	0x46, 0xf9, 0x87, 0x03, 0xf8, 0x54, 0xdc, 0x12, 0x77, 0xef, 0xa9, 0xf4, 0x6b, 0xee, 0x9d, 0xbd,
	0xf6, 0x95, 0xf8, 0xd7, 0x97, 0x8a, 0x8b, 0x9a, 0x69, 0xf2, 0xdf, 0xd1, 0xbf, 0x46, 0x8b, 0xbb,
	0xdd, 0x21, 0x64, 0xfb, 0x43, 0xc8, 0x7e, 0x1f, 0x42, 0xf6, 0xfd, 0x18, 0x3a, 0xfb, 0x63, 0xe8,
	0xfc, 0x3c, 0x86, 0xce, 0x97, 0xd7, 0xa5, 0xb6, 0x55, 0xab, 0x44, 0x8e, 0x8d, 0x6c, 0xde, 0xae,
	0x49, 0xa3, 0x24, 0x5d, 0xe3, 0xbc, 0x81, 0x6e, 0xde, 0x77, 0xa8, 0x76, 0x35, 0x2f, 0x51, 0xda,
	0x6f, 0x1b, 0x20, 0x75, 0xdd, 0xa3, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x85, 0xc0, 0xa1,
	0xf0, 0x0d, 0x02, 0x00, 0x00,
}

func (m *MsgSubmitBundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BundleFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Transactions[iNdEx])
			copy(dAtA[i:], m.Transactions[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Transactions[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBundleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBundleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBundleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BundleId) > 0 {
		i -= len(m.BundleId)
		copy(dAtA[i:], m.BundleId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BundleId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitBundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Transactions) > 0 {
		for _, b := range m.Transactions {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = m.BundleFee.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSubmitBundleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BundleId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitBundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, make([]byte, postIndex-iNdEx))
			copy(m.Transactions[len(m.Transactions)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BundleFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBundleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBundleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBundleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundleId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
