// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/tx.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitBundle represents a message to submit a bundle of transactions
type SubmitBundleRequest struct {
	Transactions [][]byte `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BlockHeight  int64    `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *SubmitBundleRequest) Reset()         { *m = SubmitBundleRequest{} }
func (m *SubmitBundleRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitBundleRequest) ProtoMessage()    {}
func (*SubmitBundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2871739d4618116, []int{0}
}
func (m *SubmitBundleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitBundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitBundleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitBundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBundleRequest.Merge(m, src)
}
func (m *SubmitBundleRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubmitBundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBundleRequest proto.InternalMessageInfo

func (m *SubmitBundleRequest) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *SubmitBundleRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type SubmitBundleResponse struct {
	BundleId string `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
}

func (m *SubmitBundleResponse) Reset()         { *m = SubmitBundleResponse{} }
func (m *SubmitBundleResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitBundleResponse) ProtoMessage()    {}
func (*SubmitBundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2871739d4618116, []int{1}
}
func (m *SubmitBundleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitBundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitBundleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitBundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBundleResponse.Merge(m, src)
}
func (m *SubmitBundleResponse) XXX_Size() int {
	return m.Size()
}
func (m *SubmitBundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBundleResponse proto.InternalMessageInfo

func (m *SubmitBundleResponse) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func init() {
	proto.RegisterType((*SubmitBundleRequest)(nil), "seiprotocol.seichain.mev.SubmitBundleRequest")
	proto.RegisterType((*SubmitBundleResponse)(nil), "seiprotocol.seichain.mev.SubmitBundleResponse")
}

func init() { proto.RegisterFile("v1/tx.proto", fileDescriptor_c2871739d4618116) }

var fileDescriptor_c2871739d4618116 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x1b, 0x0b, 0x62, 0xa7, 0x59, 0xc5, 0x2e, 0x42, 0x85, 0xa1, 0x76, 0xd5, 0x85, 0x99,
	0xa1, 0xd6, 0x27, 0x28, 0x28, 0xba, 0x70, 0x93, 0x82, 0x0b, 0x11, 0x4a, 0x66, 0x7a, 0x4d, 0x86,
	0x66, 0x72, 0x6b, 0x66, 0x12, 0xd4, 0xa7, 0xf0, 0xb1, 0x5c, 0x76, 0xe9, 0x52, 0x9a, 0x17, 0x11,
	0x27, 0x1b, 0x0b, 0x0a, 0xee, 0x0e, 0xdf, 0x39, 0x9c, 0xfb, 0x43, 0xfa, 0xf5, 0x94, 0xdb, 0x67,
	0xb6, 0x29, 0xd1, 0x62, 0x10, 0x1a, 0x50, 0x4e, 0x49, 0xcc, 0x99, 0x01, 0x25, 0xb3, 0x44, 0x15,
	0x4c, 0x43, 0x3d, 0x1c, 0xa4, 0x98, 0xa2, 0xb3, 0xf8, 0xb7, 0x6a, 0xf3, 0x43, 0x2a, 0xd1, 0x68,
	0x34, 0x5c, 0x24, 0x06, 0x78, 0x3d, 0x15, 0x60, 0x93, 0x29, 0x97, 0xa8, 0x8a, 0xd6, 0x1f, 0x3f,
	0x90, 0xe3, 0x45, 0x25, 0xb4, 0xb2, 0xf3, 0xaa, 0x58, 0xe5, 0x10, 0xc3, 0x53, 0x05, 0xc6, 0x06,
	0x63, 0xe2, 0xdb, 0x32, 0x29, 0x4c, 0x22, 0xad, 0xc2, 0xc2, 0x84, 0x07, 0xa3, 0xee, 0xc4, 0x8f,
	0xf7, 0x58, 0x70, 0x4a, 0x7c, 0x91, 0xa3, 0x5c, 0x2f, 0x33, 0x50, 0x69, 0x66, 0xc3, 0xee, 0xc8,
	0x9b, 0x74, 0xe3, 0xbe, 0x63, 0xd7, 0x0e, 0x8d, 0x67, 0x64, 0xb0, 0xdf, 0x6e, 0x36, 0x58, 0x18,
	0x08, 0x4e, 0x48, 0x4f, 0x38, 0xb2, 0x54, 0xab, 0xd0, 0x1b, 0x79, 0x93, 0x5e, 0x7c, 0xd4, 0x82,
	0x9b, 0xd5, 0xf9, 0x2b, 0xe9, 0xdd, 0x5e, 0xde, 0x2d, 0xa0, 0xac, 0xa1, 0x0c, 0x34, 0xf1, 0x7f,
	0x36, 0x04, 0x11, 0xfb, 0xeb, 0x01, 0xec, 0x97, 0x3b, 0x86, 0xec, 0xbf, 0xf1, 0x76, 0xb1, 0xf9,
	0xd5, 0xfb, 0x8e, 0x7a, 0xdb, 0x1d, 0xf5, 0x3e, 0x77, 0xd4, 0x7b, 0x6b, 0x68, 0x67, 0xdb, 0xd0,
	0xce, 0x47, 0x43, 0x3b, 0xf7, 0x67, 0xa9, 0xb2, 0x59, 0x25, 0x98, 0x44, 0xcd, 0xf5, 0xc5, 0xda,
	0x28, 0xe4, 0x46, 0xe5, 0x18, 0x69, 0xa8, 0x23, 0x37, 0x40, 0x54, 0x8f, 0x51, 0x8a, 0xdc, 0xbe,
	0x6c, 0xc0, 0x88, 0x43, 0x87, 0x66, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x71, 0x2c, 0x55,
	0xbc, 0x01, 0x00, 0x00,
}

func (m *SubmitBundleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitBundleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitBundleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Transactions[iNdEx])
			copy(dAtA[i:], m.Transactions[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Transactions[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	return len(dAtA) - i, nil
}

func (m *SubmitBundleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitBundleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitBundleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BundleId) > 0 {
		i -= len(m.BundleId)
		copy(dAtA[i:], m.BundleId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BundleId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubmitBundleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, b := range m.Transactions {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	return n
}

func (m *SubmitBundleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BundleId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubmitBundleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitBundleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitBundleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, make([]byte, postIndex-iNdEx))
			copy(m.Transactions[len(m.Transactions)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitBundleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitBundleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitBundleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundleId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
